name: build_at_app_bundler_job
description: Build at_app_bundler

runs:
  using: composite

  steps:
    - name: Build at_app_bundler
      shell: bash
      run: |
        BUNDLER_PATH="$GITHUB_WORKSPACE/packages/at_app_bundler"
        BRICK_PATH="$BUNDLER_PATH/bricks"

        # Build the mason bricks in at_app_create and output them into at_app
        for BRICK in "$BRICK_PATH"/*;
        do
          dart pub global run mason_cli:mason bundle -t dart -o "$BUNDLER_PATH/lib/src/bundles/$(basename "$BRICK")" "$BRICK";
        done

        # Dart Format
        # Cannot format at_app_bundler directory directly
        # it will non-zero exit due to the dart templates in the bricks directory
        dart format -l 120 "$GITHUB_WORKSPACE/packages/at_app_bundler/lib";
        dart format -l 120 "$GITHUB_WORKSPACE/packages/at_app_bundler/bin";
