version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for packages
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
