version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for packages
  - package-ecosystem: "pub"
    directory: "/packages/at_app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/at_app_bundler"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/at_app_create"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/at_app_flutter"
    schedule:
      interval: "daily"
  # Maintain dependencies for templates
  - package-ecosystem: "pub"
    directory: "/templates/demos/chit_chat"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/templates/demos/snackbar"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/templates/demos/snackbar_sender"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/templates/templates/app"
    schedule:
      interval: "daily"
