name: build_at_app_create_job
description: Build at_app_create

runs:
  using: composite

  steps:
    - name: Build at_app_create
      shell: bash
      run: |
        AT_APP_CREATE_PATH="$GITHUB_WORKSPACE/packages/at_app_create"
        BRICK_PATH="$AT_APP_CREATE_PATH/bricks"

        # Run build_runner build on json_serializable classes
        cd "$AT_APP_CREATE_PATH" || exit 1
        dart run build_runner build --delete-conflicting-outputs
        cd "$GITHUB_WORKSPACE" || exit 1

        # Build the mason bricks in at_app_create and output them into at_app
        for BRICK in "$BRICK_PATH"/*;
        do
          dart pub global run mason_cli:mason bundle -t dart -o "$AT_APP_CREATE_PATH/lib/src/bundles/$(basename "$BRICK")" "$BRICK";
        done

        # Dart Format
        # Cannot format at_app_create directory directly
        # it will non-zero exit due to the dart templates in the bricks directory
        dart format -l 120 "$GITHUB_WORKSPACE/packages/at_app_create/lib";
