name: build_job
description: Build at_app repo

runs:
  using: composite

  steps:
    - name: Build at_app_bundler
      uses: ./.github/composite/build_at_app_bundler

    - name: Build at_app_create
      uses: ./.github/composite/build_at_app_create

    - name: Bundle templates into at_app
      uses: ./.github/composite/bundle_templates

    - name: Build at_app
      uses: ./.github/composite/build_at_app
