name: install_dependencies_job
description: Install dependencies for at_app repo

runs:
  using: composite
  steps:
    - name: Install melos
      run: dart pub get
      shell: bash

    - name: Bootstrap project with melos
      run: dart run melos bootstrap
      shell: bash

    - name: Install build_runner
      run: dart pub global activate build_runner
      shell: bash

    - name: Install mason_cli
      run: dart pub global activate mason_cli
      shell: bash
