name: snackbar_sender_template
publish_to: none
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  at_client_mobile: ^3.2.9
  at_utils: ^3.0.13
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.1.1
  at_onboarding_flutter: ^6.1.0
  biometric_storage: ^5.0.0+3

env:
  override: true

env_override:
  NAMESPACE: fourballcorporate9
  API_KEY: 477b-876u-bcez-c42z-6a3d
