name: at_app
description: A command line tool to help developers build an atPlatform application.
version: 5.0.0
repository: https://github.com/atsign-foundation/at_app/tree/trunk/packages/at_app/
homepage: https://atsign.dev/

executables:
  at_app: at_app

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  at_app_create: 0.4.0
  mason: 0.1.0-dev.50
  args: ^2.2.0
  at_commons: ^3.0.0
  at_utils: ^3.0.0
  collection: ^1.16.0
  io: ^1.0.3
  logger: ">=1.0.0 <3.0.0"
  path: ^1.8.0
  pub_cache: ^0.3.1
  pub_semver: ^2.0.0
  pubspec: ^2.0.1
  tabular: ^0.6.3+1
  yaml: ^3.1.0
  meta: ^1.7.0
  chalk: ^1.2.0

dev_dependencies:
  flutter_lints: ">=1.0.4 <3.0.0"
  test: ^1.16.8
  build_runner: ^2.1.7
  build_version: ^2.1.0
  lints: ">=1.0.0 <3.0.0"
  mockito: ^5.1.0
