name: chit_chat_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_client_mobile: ^3.2.9
  at_utils: ^3.0.13
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  at_chat_flutter: ^3.0.7
  at_contacts_flutter: ^4.0.10
  at_app_flutter: ^5.1.1
  at_onboarding_flutter: ^6.1.0
  biometric_storage: ^4.1.3

env:
  override: true

env_override:
  NAMESPACE: tapiradded13
  API_KEY: 477b-876u-bcez-c42z-6a3d

