name: at_backupkey_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.0
  at_backupkey_flutter: ^4.0.2
  cupertino_icons: ^1.0.0
  at_client_mobile: ^3.2.3
  biometric_storage: ^3.0.1

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

