name: generated_app_job
description: Build and analyze a generated app

inputs:
  type:
    required: true
    description: Can be one of "template" "sample" "demo"
  name:
    required: true
    description: Name of the template

runs:
  using: composite
  steps:
    - name: Build generated app
      uses: ./.github/composite/build_generated
      with:
        type: ${{inputs.type}}
        name: ${{inputs.name}}

    - name: Analyze generated app
      working-directory: ./build/${{inputs.type}}/${{inputs.name}}
      run: dart analyze
      shell: bash
