name: generated_app_job
description: Build and analyze a generated app

inputs:
  demo_name:
    required: false
    description: Name of the demo template (empty for default template)

runs:
  using: composite
  steps:
    - name: Build generated app
      uses: ./.github/composite/build_generated
      with:
        name: ${{inputs.name}}

    - name: Analyze generated app
      working-directory: ./build/${{inputs.name || 'app'}}
      run: dart analyze
      shell: bash
