name: snackbar_template
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  at_client_mobile: ^3.2.6
  at_utils: ^3.0.11
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  timer_builder: ^2.0.0
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.3
  biometric_storage: ^4.1.3

env:
  override: true

env_override:
  NAMESPACE: fourballcorporate9
  API_KEY: 477b-876u-bcez-c42z-6a3d
