name: at_chat_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.3
  at_chat_flutter: ^3.0.6
  biometric_storage: ^4.1.3

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

